### ISSUE TITLE
Graphical Issues & Island Unresponciveness 

### ISSUE THREAD

**Issue by 112cxyz** [crissNb/Dynamic-Island-Sketchybar#5] opened 2022-10-03 22:21 UTC
I pulled the latest commit and sadly the bar is now completely unresponsive. 

https://user-images.githubusercontent.com/78795456/193696280-6a35ce6d-b8e6-4804-8d1c-70e00e768504.mov

**Comment by 112cxyz** [comment] 2022-10-03 22:27
running sketchybarc:


/Users/name/.config/sketchybar/items/dynamic_island.sh: line 5: /Users/name/.config/sketchybar/plugins/dynamic_island/data/active: No such file or directory

**Comment by crissNb** [comment] 2022-10-03 22:29
Ahh, it seems like the "data" folder is missing. I've added data folder in .gitignore, as it included my personal notification data etc. 
The cache files can be generated on their own, it's just that data folders have to be made manually. I'll make a commit that fixes this shortly.

**Comment by 112cxyz** [comment] 2022-10-03 22:36
running touch on those files causes the bar to respond but still with graphical problems and severe lag (with notifs disabled) there is constant displaying of the now playing song like it is being polled every few seconds. Titles mismatching is now an issue same with album art.

https://user-images.githubusercontent.com/78795456/193697939-3d52f353-bb3b-4704-9431-53ea4c8d7408.mov

**Comment by crissNb** [comment] 2022-10-03 23:06
I'm not really able to reproduce the severe lag problem. From the looks like it, it seems like more than one feature is trying to access the dynamic island at the same time (which it shouldn't happen after I "fixed" earlier today; but the corners of dynamic islands seem to be constantly changing).
It's also quite odd how the previous commit (before the breaking change) didn't cause as much graphical issues as after the commit. 
Essentially, each feature should prevent the dynamic island to change for a set duration while it's being active (which is checked via a "active" file in data/active). Except for the feature of same type (e.g. dynamic island currently drawing "music", it can be instantly replaced if music island gets activated). This request can take over dynamic island instantly. This might be the problem.

Could you also try disabling volume feature (also by commenting out in `~/.config/sketchybar/plugins/dynamic_island.sh`)? This feature comes disabled by default with the new commit, but just in case. Volume module is the only module that is not currently supported by this "only one island at a time" feature.

I will be doing more investigations tomorrow (it's getting late here).

**Comment by 112cxyz** [comment] 2022-10-03 23:19
Much fewer issues and app switching now works. There is less lag but still graphical glitches.

https://user-images.githubusercontent.com/78795456/193702417-312bda19-ae8f-419e-8670-5f11830e999f.mov

I will be able to help tomorrow more it's currently 00:17 for me so yeah. I will send more updates and ill look around fixing files.  

if you could add me on discord it would make sending issues much faster: 112c#7777

**Comment by 112cxyz** [comment] 2022-10-04 11:27
I edited my config to allow notifications, I had set it up correctly but it wouldn't run. So I read the python file and needed to run:

`pip3 install biplist`

https://user-images.githubusercontent.com/78795456/193800902-9e6ce24b-ed09-43a2-b4f8-4adceb8ecd69.mov

**Comment by crissNb** [comment] 2022-10-04 18:23
> So I read the python file and needed to run: pip3 install biplist

This is something I realised yesterday after the initial release, so I've made changes to the requirement section in README.md.

As for the graphical glitches that is still occurring, something odd is that the dynamic island opens up far slower on your end. Might be a long shot, but could you try setting the `update_freq` to something bigger like 5 in `~/.config/sketchybar/items/dynamic_island.sh` (line 26)? Remember to restart the SketchyBar to take effect (`brew services restart sketchybar`).

There also seem to be parsing errors when handling notifications (and notification island in general), I'll need to look into that problem as well.

**Comment by 112cxyz** [comment] 2022-10-04 18:35
I set it to 5 at first still glitching and a bit slow, and then changed it to 15. I have also realised its truncation of song names are  inacurate. 


With Update Frequencey 15:

https://user-images.githubusercontent.com/78795456/193898100-d4b3c1c6-7183-4f5f-8d96-2e20fa81d4fd.mov

Update Frequencey 5:

https://user-images.githubusercontent.com/78795456/193898229-47509c03-a7c7-45f2-8671-0b0257358642.mov

**Comment by crissNb** [comment] 2022-10-04 18:52
Hmm. It's weird how the island does not glitch at all when it's showing "Resumed" (and runs at intended speed). I was going to suggest retrieving album artwork might be a potential issue, but if that's the case, it shouldn't glitch the dynamic island when it's closing.

**Comment by crissNb** [comment] 2022-11-11 12:58
Is this issue still present? Ever since the integration of the new helper program, the graphical unresponsiveness issue no longer seems to be as big of an issue.

**Comment by crissNb** [comment] 2022-11-25 13:01
closing due to inactivity

**Closed by crissNb** 2022-11-25 13:01 UTC
